-- Initialize tables required by case-search and case-admin pages
-- Safe to run multiple times.

create extension if not exists pgcrypto;

create table if not exists public.user_profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  issuing_place text,
  id_number text,
  gender text,
  birth_date text,
  current_identity text,
  household_registration text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.user_profiles add column if not exists issuing_place text;
alter table if exists public.user_profiles add column if not exists id_number text;
alter table if exists public.user_profiles add column if not exists gender text;
alter table if exists public.user_profiles add column if not exists birth_date text;
alter table if exists public.user_profiles add column if not exists current_identity text;
alter table if exists public.user_profiles add column if not exists household_registration text;
alter table if exists public.user_profiles add column if not exists id uuid default gen_random_uuid();
update public.user_profiles set id = gen_random_uuid() where id is null;
alter table public.user_profiles alter column id set default gen_random_uuid();
alter table public.user_profiles alter column id set not null;

do $$
declare
  current_primary_key text;
  id_attribute smallint;
  primary_key_uses_id boolean;
begin
  select attnum into id_attribute
  from pg_attribute
  where attrelid = 'public.user_profiles'::regclass and attname = 'id';

  select conname, conkey = array[id_attribute]
  into current_primary_key, primary_key_uses_id
  from pg_constraint
  where conrelid = 'public.user_profiles'::regclass and contype = 'p';

  if not coalesce(primary_key_uses_id, false) then
    if current_primary_key is not null then
      execute format('alter table public.user_profiles drop constraint %I', current_primary_key);
    end if;
    alter table public.user_profiles add constraint user_profiles_pkey primary key (id);
  end if;
end
$$;

create index if not exists idx_user_profiles_auth_user_id on public.user_profiles(auth_user_id);

create table if not exists public.user_records (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  profile_id uuid references public.user_profiles(id) on delete cascade,
  title text not null default '未命名案件',
  info_text text not null default '',
  wanted_date text,
  case_category text,
  current_address text,
  filing_unit text,
  case_summary text,
  notes text,
  application_request text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.user_records add column if not exists wanted_date text;
alter table if exists public.user_records add column if not exists case_category text;
alter table if exists public.user_records add column if not exists current_address text;
alter table if exists public.user_records add column if not exists filing_unit text;
alter table if exists public.user_records add column if not exists case_summary text;
alter table if exists public.user_records add column if not exists notes text;
alter table if exists public.user_records add column if not exists application_request text;
alter table if exists public.user_records add column if not exists profile_id uuid references public.user_profiles(id) on delete cascade;

update public.user_records as record
set profile_id = profile.id
from public.user_profiles as profile
where record.profile_id is null
  and profile.auth_user_id = record.auth_user_id;

create table if not exists public.record_photos (
  id bigint generated by default as identity primary key,
  record_id uuid not null references public.user_records(id) on delete cascade,
  photo_url text not null,
  caption text,
  created_at timestamptz not null default now()
);

create table if not exists public.record_messages (
  id bigint generated by default as identity primary key,
  record_id uuid not null references public.user_records(id) on delete cascade,
  sender_role text not null default 'staff',
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.video_chat_messages (
  id bigint generated by default as identity primary key,
  channel text not null,
  sender text not null default '访客',
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_user_records_auth_user_id on public.user_records(auth_user_id);
create index if not exists idx_user_records_profile_id on public.user_records(profile_id);
create index if not exists idx_record_photos_record_id on public.record_photos(record_id);
create index if not exists idx_record_messages_record_id on public.record_messages(record_id);
create index if not exists idx_video_chat_messages_channel_id on public.video_chat_messages(channel, id);

alter table public.user_profiles enable row level security;
alter table public.user_records enable row level security;
alter table public.record_photos enable row level security;
alter table public.record_messages enable row level security;
alter table public.video_chat_messages enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'profile_select_own'
  ) then
    create policy profile_select_own on public.user_profiles
      for select to authenticated
      using (auth.uid() = auth_user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'profile_upsert_own'
  ) then
    create policy profile_upsert_own on public.user_profiles
      for all to authenticated
      using (auth.uid() = auth_user_id)
      with check (auth.uid() = auth_user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_records' and policyname = 'records_select_own'
  ) then
    create policy records_select_own on public.user_records
      for select to authenticated
      using (auth.uid() = auth_user_id);
  end if;

  drop policy if exists records_modify_own on public.user_records;
  create policy records_modify_own on public.user_records
    for all to authenticated
    using (auth.uid() = auth_user_id)
    with check (
      auth.uid() = auth_user_id
      and exists (
        select 1 from public.user_profiles profile
        where profile.id = profile_id and profile.auth_user_id = auth.uid()
      )
    );

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'record_photos' and policyname = 'photos_select_own'
  ) then
    create policy photos_select_own on public.record_photos
      for select to authenticated
      using (
        exists (
          select 1 from public.user_records r
          where r.id = record_id and r.auth_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'record_photos' and policyname = 'photos_modify_own'
  ) then
    create policy photos_modify_own on public.record_photos
      for all to authenticated
      using (
        exists (
          select 1 from public.user_records r
          where r.id = record_id and r.auth_user_id = auth.uid()
        )
      )
      with check (
        exists (
          select 1 from public.user_records r
          where r.id = record_id and r.auth_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'record_messages' and policyname = 'messages_select_own'
  ) then
    create policy messages_select_own on public.record_messages
      for select to authenticated
      using (
        exists (
          select 1 from public.user_records r
          where r.id = record_id and r.auth_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'record_messages' and policyname = 'messages_modify_own'
  ) then
    create policy messages_modify_own on public.record_messages
      for all to authenticated
      using (
        exists (
          select 1 from public.user_records r
          where r.id = record_id and r.auth_user_id = auth.uid()
        )
      )
      with check (
        exists (
          select 1 from public.user_records r
          where r.id = record_id and r.auth_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'video_chat_messages' and policyname = 'video_chat_messages_select_authenticated'
  ) then
    create policy video_chat_messages_select_authenticated on public.video_chat_messages
      for select to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'video_chat_messages' and policyname = 'video_chat_messages_insert_authenticated'
  ) then
    create policy video_chat_messages_insert_authenticated on public.video_chat_messages
      for insert to authenticated
      with check (true);
  end if;
end
$$;

notify pgrst, 'reload schema';

insert into storage.buckets (id, name, public)
values ('case-photos', 'case-photos', true)
on conflict (id) do update set public = true;

drop policy if exists case_photos_authenticated_insert on storage.objects;
create policy case_photos_authenticated_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'case-photos');

drop policy if exists case_photos_authenticated_update on storage.objects;
create policy case_photos_authenticated_update on storage.objects
  for update to authenticated
  using (bucket_id = 'case-photos')
  with check (bucket_id = 'case-photos');
